version: "3"
services:
   kameleoon:
      build: kameleoon
      deploy:
         resources: 
             limits: 
                cpus: '0.5'
                memory: 300M
             reservations:
                cpus: '0.3'
                memory: 200M    
      ports: 
            - 8080:8080
                